module.exports = {
  A: 'Apple',
  B: 'Beech',
  C: 'Ceder',
  D: 'Dogwood',
  E: 'Elm',
  F: 'Fir',
  G: 'Ginkgo',
  H: 'Horsechestnut',
  I: 'Ilex',
  J: 'Juniper',
  K: 'Kentucky Coffeetree',
  L: 'Linden',
  M: 'Mulberry',
  N: 'Nannyburg',
  O: 'Oak',
  P: 'Pine',
  Q: 'Quaking Aspen',
  R: 'Redwood',
  S: 'Sycamore',
  T: 'Tree of Heaven',
  U: 'Umbrella Tree',
  V: 'Viberum',
  W: 'Weeping Willow',
  X: 'Xanthoxylum',
  '': '',
  Y: 'Yellow Wood',
  Z: 'Zelkova',
};